- id: doi:10.1002/pro.70167
  type: paper
  description: Bringing together simulation and experiment, we identify residues involved in protein binding for human cis-prenyltransferase to the membrane.
  image: ../images/pubpic/hcispt.png
  tags:
    - membrane-protein interaction
    - small molecule
    - collaboration
    - healthy

- id: doi:10.1002/csc2.70066
  type: review
  description: Review article on sorgoleone, a natural herbicide made by sorghum.
  tags:
    - small molecule
    - collaboration
    - planty

- id: doi:10.1021/acssynbio.4c00290
  type: paper
  description: Combination of timeseries for light emitted by encapsulated luciferases, which gives us a quantitative estimate for permeability for substrates and products. Turns out open shells missing pentameric capping units are about 50x more permeable.
  image: https://pubs.acs.org/toc/asbcd6/14/5
  tags:
    - collaboration
    - microcompartment
